apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-go-test
  namespace: flux-go-test
spec:
  releaseName: flux-go-test
  chart:
    spec:
      chart: flux-go-test
      sourceRef:
        kind: HelmRepository
        name: flux-go-test
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
    image:
      pullPolicy: Always
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://opentelemetry-collector.otel.svc.cluster.local:4317"