apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-go-test
spec:
  chartRef:
    kind: OCIRepository
    name: flux-go-test
    namespace: flux-system
  interval: 10m
  values:
    replicaCount: 2