apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-go-test
  namespace: flux-go-test
spec:
  interval: 1m
  url: https://github.com/jmpargana/flux-go-test
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    
