apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - opentelemetry-collector.yaml
  - opentelemetry-operator.yaml
  - grafana.yaml