apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h  
  values:
    loki:
      auth_enabled: false

      storage:
        type: filesystem

      commonConfig:
        path_prefix: /var/loki