apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h