---
apiVersion: v1
kind: Namespace
metadata:
  name: otel
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otel
  namespace: otel
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: otel
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: otel
      interval: 12h
  values:
    image:
      repository: otel/opentelemetry-collector-k8s
    mode: deployment