apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: otel
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: otel
      interval: 12h
