apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: grafana
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: grafana
      interval: 12h